version: "2.1"

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}
        - AGENT_ID=${AGENT_ID}
        - APP_NAME=${APP_NAME}
        - SPRING_PROFILES=${SPRING_PROFILES}
    container_name: "java"
    image: "smartopsdemo"
    ports:
      - "${APP_PORT:-8443}:8080"

    volumes_from:
      - container:pinpoint-agent
    environment:
     JAVA_OPTS: "-javaagent:/pinpoint-agent/pinpoint-bootstrap-${PINPOINT_VERSION}.jar -Dpinpoint.agentId=${AGENT_ID} -Dpinpoint.applicationName=smartopsdemo -Dpinpoint.profiler.profiles.active=MyProfile  -Dpinpoint.config=$MY_EXTERNAL_CONFIG_PATH"
networks:
  default:
    external:
      name: pinpoint-agent_pinpoint
